export enum SoulBeastElement {
  FIRE = 1,
  WATER = 2,
  WIND = 3,
  EARTH = 4,
  LIGHT = 5,
  DARK = 6,
}

export enum SoulBeastRole {
  ATTACK = 1,
  TANK = 2,
  SUPPORT = 3,
}

export enum SoulBeastTrait {
  HEAVY = "重",
  FRENZY = "狂",
  CURSE = "咒",
  SAVE = "存",
  CHARGE = "蓄",
}

export interface SoulBeastConfig {
  id: number;
  name: string;
  rarity: number;
  element: SoulBeastElement;
  role: SoulBeastRole;
  trait: SoulBeastTrait;
  iconFrameName: string;
  maxLevel: number;
  maxStar: number;
  baseShardNeed: number;
}

export const soulBeastConfigs: SoulBeastConfig[] = [
  {
    id: 30001,
    name: "烈焰",
    rarity: 2,
    element: SoulBeastElement.FIRE,
    role: SoulBeastRole.ATTACK,
    trait: SoulBeastTrait.HEAVY,
    iconFrameName: "SoulBeast_1",
    maxLevel: 50,
    maxStar: 5,
    baseShardNeed: 20,
  },
  {
    id: 30002,
    name: "阿璃",
    rarity: 2,
    element: SoulBeastElement.WATER,
    role: SoulBeastRole.ATTACK,
    trait: SoulBeastTrait.FRENZY,
    iconFrameName: "SoulBeast_2",
    maxLevel: 50,
    maxStar: 5,
    baseShardNeed: 20,
  },
  {
    id: 30003,
    name: "地雷鱼",
    rarity: 2,
    element: SoulBeastElement.WIND,
    role: SoulBeastRole.SUPPORT,
    trait: SoulBeastTrait.CURSE,
    iconFrameName: "SoulBeast_3",
    maxLevel: 50,
    maxStar: 5,
    baseShardNeed: 20,
  },
  {
    id: 30004,
    name: "凤凰鹰",
    rarity: 2,
    element: SoulBeastElement.EARTH,
    role: SoulBeastRole.TANK,
    trait: SoulBeastTrait.SAVE,
    iconFrameName: "SoulBeast_4",
    maxLevel: 50,
    maxStar: 5,
    baseShardNeed: 20,
  },
  {
    id: 30005,
    name: "熔岩犀",
    rarity: 3,
    element: SoulBeastElement.FIRE,
    role: SoulBeastRole.ATTACK,
    trait: SoulBeastTrait.CHARGE,
    iconFrameName: "SoulBeast_5",
    maxLevel: 60,
    maxStar: 5,
    baseShardNeed: 30,
  },
  {
    id: 30006,
    name: "雪原狐",
    rarity: 3,
    element: SoulBeastElement.WATER,
    role: SoulBeastRole.SUPPORT,
    trait: SoulBeastTrait.HEAVY,
    iconFrameName: "SoulBeast_6",
    maxLevel: 60,
    maxStar: 5,
    baseShardNeed: 30,
  },
  {
    id: 30007,
    name: "荒漠狼一",
    rarity: 3,
    element: SoulBeastElement.WIND,
    role: SoulBeastRole.ATTACK,
    trait: SoulBeastTrait.FRENZY,
    iconFrameName: "SoulBeast_7",
    maxLevel: 60,
    maxStar: 5,
    baseShardNeed: 30,
  },
  {
    id: 30008,
    name: "荒漠狼二",
    rarity: 3,
    element: SoulBeastElement.EARTH,
    role: SoulBeastRole.TANK,
    trait: SoulBeastTrait.CURSE,
    iconFrameName: "SoulBeast_8",
    maxLevel: 60,
    maxStar: 5,
    baseShardNeed: 30,
  },
  {
    id: 30009,
    name: "荒漠翼三",
    rarity: 4,
    element: SoulBeastElement.FIRE,
    role: SoulBeastRole.ATTACK,
    trait: SoulBeastTrait.SAVE,
    iconFrameName: "SoulBeast_9",
    maxLevel: 70,
    maxStar: 5,
    baseShardNeed: 40,
  },
  {
    id: 30010,
    name: "荒漠翼四",
    rarity: 4,
    element: SoulBeastElement.WATER,
    role: SoulBeastRole.TANK,
    trait: SoulBeastTrait.CHARGE,
    iconFrameName: "SoulBeast_10",
    maxLevel: 70,
    maxStar: 5,
    baseShardNeed: 40,
  },
  {
    id: 30011,
    name: "炎影龙一",
    rarity: 4,
    element: SoulBeastElement.WIND,
    role: SoulBeastRole.SUPPORT,
    trait: SoulBeastTrait.HEAVY,
    iconFrameName: "SoulBeast_11",
    maxLevel: 70,
    maxStar: 5,
    baseShardNeed: 40,
  },
  {
    id: 30012,
    name: "炎影龙二",
    rarity: 4,
    element: SoulBeastElement.EARTH,
    role: SoulBeastRole.TANK,
    trait: SoulBeastTrait.FRENZY,
    iconFrameName: "SoulBeast_12",
    maxLevel: 70,
    maxStar: 5,
    baseShardNeed: 40,
  },
  {
    id: 30013,
    name: "小龙壳一",
    rarity: 5,
    element: SoulBeastElement.LIGHT,
    role: SoulBeastRole.SUPPORT,
    trait: SoulBeastTrait.CURSE,
    iconFrameName: "SoulBeast_13",
    maxLevel: 80,
    maxStar: 5,
    baseShardNeed: 50,
  },
  {
    id: 30014,
    name: "小龙壳二",
    rarity: 5,
    element: SoulBeastElement.DARK,
    role: SoulBeastRole.ATTACK,
    trait: SoulBeastTrait.SAVE,
    iconFrameName: "SoulBeast_14",
    maxLevel: 80,
    maxStar: 5,
    baseShardNeed: 50,
  },
  {
    id: 30015,
    name: "小龙翼",
    rarity: 5,
    element: SoulBeastElement.FIRE,
    role: SoulBeastRole.ATTACK,
    trait: SoulBeastTrait.CHARGE,
    iconFrameName: "SoulBeast_15",
    maxLevel: 80,
    maxStar: 5,
    baseShardNeed: 50,
  },
  {
    id: 30016,
    name: "蛇龙",
    rarity: 5,
    element: SoulBeastElement.DARK,
    role: SoulBeastRole.TANK,
    trait: SoulBeastTrait.HEAVY,
    iconFrameName: "SoulBeast_16",
    maxLevel: 80,
    maxStar: 5,
    baseShardNeed: 50,
  },
];
